input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
predict_path: "models/predicts.json"
splitting_params:
  val_size: 0.3
  random_state: 17
  shuffle: True
train_params:
  model_type: "LogisticRegression"
  log_reg_max_iterations: 500
processing_params:
  use_scaler: True
feature_params:
  categorical_features:
    - "sex"
    - "fbs"
    - "restecg"
  numerical_features:
    - "cp"
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
    - "exang"
  target_col: "target"
