name: ml-project-github-actions
on: [push]
jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: fylein/python-pylint-github-action@v1
        with:
          args: pylint ml_project/ml_process
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest ml_project/tests